
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: valentines_development

test:
  <<: *default
  database: valentines_test

production:
  <<: *default
  database: valentines_production
