# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c7ee8f75eddd2b1116b3c3b911b997ef12654ade6bd8a66decf82f085811702bc74fd0f50165a279ccd24b4af579f791bc1a425e479482ea87ca79a9d7e9be1

test:
  secret_key_base: 010d4afeabf04a9416fa09ad9940fb43d8e4b2b70888039239a04eebe67f14a70b325827b3381e3d66c97077b5c3b3070bc5cb95a25cc5800403e98f3332b7db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
